// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import frc.robot.LimelightUtility;
import frc.robot.Robot;

/**
 *
 */
public class LimeLightTurn extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public LimeLightTurn() {

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    private double targetTurn;
    private boolean targetAcquired = false;
    private double ledWarmUp = 100;

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        setTimeout(5);
        LimelightUtility.EnableDriverCamera(false);
        LimelightUtility.WriteDouble("ledMode", 3); // 3 = Limelight On
        ledWarmUp = 100;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        LimelightUtility.RefreshTrackingData();
        targetAcquired = LimelightUtility.ValidTargetFound();

        if (targetAcquired) {
            targetTurn = getTargetTurn();
            Robot.driveTrain.closedLoopTurn(targetTurn);
        }
        ledWarmUp--;
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        boolean turnComplete = Robot.driveTrain.closedLoopTurnComplete(targetTurn);

        return (turnComplete && (ledWarmUp <= 0)) || isTimedOut();
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        //LimelightUtility.WriteDouble("ledMode", 1); // 1 = Limelight Off
        //LimelightUtility.EnableDriverCamera(true);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }

    private double getTargetTurn() {
        LimelightUtility.RefreshTrackingData();
        return -LimelightUtility.TargetHorizontalOffset;
    }
}
